package com.believexin.common.entity.po;

public class TViewsUsedTables {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_views_used_tables.c_viewschema
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    private String cViewschema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_views_used_tables.c_viewname
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    private String cViewname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_views_used_tables.c_tableschema
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    private String cTableschema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_views_used_tables.c_tablename
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    private String cTablename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_views_used_tables.c_viewschema
     *
     * @return the value of t_views_used_tables.c_viewschema
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    public String getcViewschema() {
        return cViewschema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_views_used_tables.c_viewschema
     *
     * @param cViewschema the value for t_views_used_tables.c_viewschema
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    public void setcViewschema(String cViewschema) {
        this.cViewschema = cViewschema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_views_used_tables.c_viewname
     *
     * @return the value of t_views_used_tables.c_viewname
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    public String getcViewname() {
        return cViewname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_views_used_tables.c_viewname
     *
     * @param cViewname the value for t_views_used_tables.c_viewname
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    public void setcViewname(String cViewname) {
        this.cViewname = cViewname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_views_used_tables.c_tableschema
     *
     * @return the value of t_views_used_tables.c_tableschema
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    public String getcTableschema() {
        return cTableschema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_views_used_tables.c_tableschema
     *
     * @param cTableschema the value for t_views_used_tables.c_tableschema
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    public void setcTableschema(String cTableschema) {
        this.cTableschema = cTableschema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_views_used_tables.c_tablename
     *
     * @return the value of t_views_used_tables.c_tablename
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    public String getcTablename() {
        return cTablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_views_used_tables.c_tablename
     *
     * @param cTablename the value for t_views_used_tables.c_tablename
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    public void setcTablename(String cTablename) {
        this.cTablename = cTablename;
    }
}