server:
  port: 9090
  servlet:
    context-path: /blood-kinship
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_aty
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/believexin/repository/*.xml
blood:
  specialTables:  v_share_slxx