package com.believexin.repository;

import com.believexin.common.entity.po.TViewsUsedTables;
import com.believexin.common.entity.po.TViewsUsedTablesExample;
import java.util.List;

public interface TViewsUsedTablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_views_used_tables
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    long countByExample(TViewsUsedTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_views_used_tables
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    int insert(TViewsUsedTables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_views_used_tables
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    int insertSelective(TViewsUsedTables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_views_used_tables
     *
     * @mbg.generated Fri Nov 02 17:27:42 CST 2018
     */
    List<TViewsUsedTables> selectByExample(TViewsUsedTablesExample example);
    
    
}